GET http://localhost:3000/users

###

POST http://localhost:4000/users/register
Content-Type: application/json

{
    "name": "ons",
    "password": "anis"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "name": "ons",
    "password": "anis"
}

###

GET  http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib25zIiwiaWF0IjoxNjE1NDQ0ODE5LCJleHAiOjE2MTU0NDQ4MzR9.G2R-4FckytJbAnvryIxktq1OujqhFcCx5S5fzPEgSz4


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib25zIiwicGFzc3dvcmQiOiIkMmIkMTAkaUVpUUFJTzdwY3ROSVZ4bWFqY2pnLk0zU1BKem5jeTVyMFc2cEhlblhRSEFOVDVwQXNqS1ciLCJpYXQiOjE2MTU0NDQ3ODd9.08o3FSahtLvoRhR6Zll98eSJQ311ZY4ceyXCwFZwMvI"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib25zIiwicGFzc3dvcmQiOiIkMmIkMTAkaUVpUUFJTzdwY3ROSVZ4bWFqY2pnLk0zU1BKem5jeTVyMFc2cEhlblhRSEFOVDVwQXNqS1ciLCJpYXQiOjE2MTU0NDQ2MTV9.DXq_Y7s9lTKQECEo-4_62BFRU5uKhqnCeW8w3pWacBg"
}

